line-length = 180
target-version = "py312"
exclude = [".git", ".mypy_cache", ".ruff_cache"]
src = ["./src"]

lint.select = ["ALL"]

lint.isort = { combine-as-imports = true }
format = { quote-style = "double", indent-style = "space" }
